
from __future__ import annotations

from pathlib import Path
from typing import Dict, Any, List
import datetime, json

from app.modules.base import ModuleResult
from app.settings import settings
from app.flywheel.slug import slugify
from app.export.packager import write_text
from app.rag.llm import LLM

def _matrix(topic: str, include_enterprise: bool) -> Dict[str, Any]:
    tiers = [
        {
            "tier": "personal",
            "intent": "solo use, personal learning, non-client projects",
            "rights": [
                "use privately",
                "print for personal use",
                "modify for yourself",
                "save backups",
                "share snippets (non-commercial)",
                "use in portfolio (non-revenue)",
            ],
            "restrictions": [
                "no resale",
                "no redistribution of source files",
                "no claiming authorship",
                "no medical/legal guarantees",
                "no use as regulated advice",
                "no removal of notices",
                "no training public models on private user data",
                "no misrepresentation of results",
                "no sublicensing",
            ],
        },
        {
            "tier": "commercial",
            "intent": "business use in internal ops or client deliverables (non-resale of the asset itself)",
            "rights": [
                "use in a business",
                "use in client work (deliver outputs, not the pack)",
                "modify and adapt",
                "bundle into internal SOPs",
                "create derivative outputs",
                "use in marketing examples (truthful)",
            ],
            "restrictions": [
                "no resale of the pack",
                "no public redistribution of editable sources",
                "no white-labeling as original",
                "no deceptive marketing claims",
                "no unlawful data collection",
                "no removal of fingerprints/watermarks",
                "no use in prohibited content",
                "no sublicensing",
                "respect opt-in and privacy laws",
            ],
        },
        {
            "tier": "resale",
            "intent": "sell derivative products created from this pack (with conditions)",
            "rights": [
                "create derivative products",
                "sell compiled outputs (PDF, rendered images, exports)",
                "sell bundles that contain your original additions",
                "use in memberships (gated access)",
                "use in courses (as teaching material)",
                "use for limited re-distribution with your value-add",
            ],
            "restrictions": [
                "do not resell raw source files as-is",
                "must add meaningful original value",
                "must keep notices in a credits section",
                "no trademark misuse",
                "no impersonation / false endorsements",
                "no prohibited content",
                "no selling user private data",
                "no removing audit/fingerprint files",
                "must provide support contact for your customers",
            ],
        },
    ]
    if include_enterprise:
        tiers.append(
            {
                "tier": "enterprise",
                "intent": "multi-seat, multi-brand, custom licensing and indemnity options",
                "rights": [
                    "multi-seat use",
                    "multi-brand deployment",
                    "custom terms (SOW)",
                    "priority updates",
                    "private training datasets allowed (local only)",
                    "custom support macros",
                ],
                "restrictions": [
                    "requires signed agreement",
                    "no public redistribution of sources",
                    "privacy requirements enforced",
                    "audit logging enabled",
                    "no prohibited content",
                    "no deceptive claims",
                    "no removal of stamps",
                    "no sublicensing without approval",
                    "comply with export controls",
                ],
            }
        )

    return {
        "topic": topic,
        "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
        "alignment": {"369": True, "phi": True, "fib": True},
        "tiers": tiers,
        "defaults": {
            "credits_line": "Includes elements generated by Phi369 EmberVault (local-only).",
            "warranty": "Provided as-is, no warranties. Review before publishing.",
        },
    }

def _fallback_markdown(topic: str, matrix: Dict[str, Any]) -> str:
    tiers = matrix["tiers"]
    lines: List[str] = []
    lines.append(f"# License Matrix — {topic}")
    lines.append("")
    lines.append("This is a **draft license matrix** you can use to price and package products.")
    lines.append("It is **not legal advice**—review and adapt for your situation.")
    lines.append("")
    lines.append("## 369 • Φ • Fib structure")
    lines.append("- **3** default tiers (personal / commercial / resale)")
    lines.append("- **6** rights per tier")
    lines.append("- **9** restrictions per tier")
    lines.append("")
    for t in tiers:
        lines.append(f"## Tier: {t['tier'].title()}")
        lines.append(f"**Intent:** {t['intent']}")
        lines.append("")
        lines.append("### Rights (6)")
        for r in t["rights"][:6]:
            lines.append(f"- {r}")
        lines.append("")
        lines.append("### Restrictions (9)")
        for r in t["restrictions"][:9]:
            lines.append(f"- {r}")
        lines.append("")
    lines.append("## Credits / Notices")
    lines.append(f"- {matrix['defaults']['credits_line']}")
    lines.append("")
    lines.append("## Warranty / Liability")
    lines.append(f"- {matrix['defaults']['warranty']}")
    lines.append("")
    return "\n".join(lines)

class LicensingMatrixGeneratorModule:
    name = "licensing_matrix_generator"

    def generate(self, topic: str, constraints: Dict[str, Any]) -> ModuleResult:
        out_dir = settings.data_dir / "artifacts" / "licensing_matrix" / slugify(topic)
        out_dir.mkdir(parents=True, exist_ok=True)

        include_enterprise = bool(constraints.get("include_enterprise", False))
        matrix = _matrix(topic, include_enterprise=include_enterprise)

        md = _fallback_markdown(topic, matrix)

        # Optional: refine with local LLM
        try:
            llm = LLM.from_settings()
            if llm.backend != "none" and bool(constraints.get("llm_refine", True)):
                prompt = (
                    "Rewrite the following license matrix as clean, plain English legal-ish draft text. "
                    "Keep the 3/6/9 structure per tier. Do not add risky claims. "
                    "Return Markdown only.\n\n" + md
                )
                md = llm.chat([
                    {"role": "system", "content": "You are a careful product licensing drafter. Be concise and practical."},
                    {"role": "user", "content": prompt},
                ])
        except Exception:
            pass

        write_text(out_dir / "LICENSE_MATRIX.md", md)
        write_text(out_dir / "license_matrix.json", json.dumps(matrix, indent=2))
        write_text(out_dir / "CLAUSE_LIBRARY.md", (
            "# Clause Library (369)\n\n"
            "Use these as building blocks across licenses and product pages.\n\n"
            "## 3 Core\n- Scope\n- Restrictions\n- Liability\n\n"
            "## 6 Operational\n- Attribution\n- Refunds\n- Updates\n- Support\n- Privacy\n- Termination\n\n"
            "## 9 Safety\n- No guarantees\n- No medical/legal claims\n- Opt-in only\n- No resale of sources\n- No prohibited content\n- No impersonation\n- No spyware\n- Respect privacy\n- Respect trademarks\n"
        ))

        return ModuleResult(
            artifact_paths=[str(out_dir / "LICENSE_MATRIX.md"), str(out_dir / "license_matrix.json"), str(out_dir / "CLAUSE_LIBRARY.md")],
            metadata={"include_enterprise": include_enterprise}
        )
